#!/bin/bash
#liste=(1 2 3 4 5 6 7 8 9 10)
#echo "Quel nombre voulez-vous afficher la table de multiplication ?"
#read nbre
nbre=$1
affTABLE() {


	for((i=1; i<=10; i++))
	do
		result=$(($nbre*$i))
		echo "$i * $nbre = $result"
	done
	
	
	#for i in ${liste[*]}
	#do
	#	result=$(($i*$nbre))
	#	echo "$i * $nbre = $result"
	#done
}
affTABLE



